use_frameworks!

platform :ios, '8.0'

target 'TGCommunity_Example' do
  pod 'TGCommunity', :path => '../'

  target 'TGCommunity_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
